import { createContext, PropsWithChildren, useContext, useMemo, useState } from "react";

export type AppLang = "bn" | "en";

type LanguageContextValue = {
  lang: AppLang;
  setLang: (lang: AppLang) => void;
  toggleLang: () => void;
  t: typeof copy.bn;
};

const copy = {
  bn: {
    appName: "বাইতুন নাজাত",
    switchLang: "EN",
    home: "হোম",
    homeTab: "হোম",
    prayer: "নামাজের সময়সূচি",
    prayerTab: "সময়",
    gallery: "গ্যালারি",
    donate: "দান",
    donateTab: "দান",
    guides: "গাইড",
    campaigns: "ক্যাম্পেইন",
    announcements: "ঘোষণা",
    notifications: "নোটিফিকেশন",
    notificationsIntro: "নামাজের সময় পরিবর্তন ও গুরুত্বপূর্ণ আপডেট এখানে দেখা যাবে।",
    markAllRead: "সব পড়া হয়েছে",
    unread: "নতুন",
    read: "পড়া হয়েছে",
    noNotifications: "এখনও কোনো নোটিফিকেশন নেই।",
    welcomeEyebrow: "শান্তির সান্নিধ্যে স্বাগতম",
    welcomeTitle: "শান্তি, সালাত ও কমিউনিটির এক নির্ভরতার স্থান।",
    exploreCommunity: "কমিউনিটি দেখুন",
    viewCampaigns: "ক্যাম্পেইন দেখুন",
    todayHijri: "আজকের হিজরি তারিখ",
    live: "লাইভ",
    upcomingPrayer: "পরবর্তী সালাত",
    adhan: "আযান",
    iqamah: "ইকামাহ",
    fullSchedule: "পূর্ণ সময়সূচি",
    dailyWisdom: "দৈনিক হাদিস",
    namazGuide: "নামাজ গাইড",
    guidesHadith: "গাইড ও হাদিস লাইব্রেরি",
    quickLinks: "দ্রুত লিংক",
    openSection: "সেকশন খুলুন",
    recentUpdates: "সাম্প্রতিক আপডেট",
    readMore: "আরও পড়ুন",
    donorNamePlaceholder: "দাতার নাম",
    amountPlaceholder: "১০০০",
    bkashPlaceholder: "০১XXXXXXXXX",
    transactionPlaceholder: "TRX123456",
    notePlaceholder: "ঐচ্ছিক নোট",
    missingFields: "তথ্য অসম্পূর্ণ",
    missingFieldsText: "প্রয়োজনীয় অনুদানের তথ্য পূরণ করুন।",
    submitted: "জমা হয়েছে",
    submittedText: "অনুদান যাচাইয়ের জন্য জমা হয়েছে।",
    submissionFailed: "জমা দেওয়া ব্যর্থ",
    tryAgain: "আবার চেষ্টা করুন।",
    donorQuote: "\"কিয়ামতের দিনে মুমিনের ছায়া হবে তার সদকা।\"",
    donorQuoteSource: "প্রবক্তা মুহাম্মাদ (সা.)",
    sacredSpaces: "পবিত্র প্রাঙ্গণ",
    visualJourney: "বাইতুন নাজাত জামে মসজিদের একটি চিত্রভ্রমণ।",
    allFrames: "সব ছবি",
    interior: "ইন্টেরিয়র",
    exterior: "এক্সটেরিয়র",
    prayerSpace: "সালাতের স্থান",
    discoverMore: "আরও মুহূর্ত দেখুন",
    currentPrayer: "বর্তমান সালাত",
    dailyTimings: "দৈনিক সময়সূচি",
    liveSchedule: "লাইভ সময়সূচি",
    stepPrayer: "ধাপে ধাপে সালাত",
    stepPrayerDesc: "সালাত ও পবিত্রতার জন্য ভিজ্যুয়াল ও টেক্সট গাইড।",
    investAkhirah: "আপনার আখিরাতের জন্য বিনিয়োগ করুন",
    donateIntro: "আপনার অনুদান আল্লাহর ঘর রক্ষণাবেক্ষণ ও কমিউনিটি সেবাকে এগিয়ে নেয়।",
    sadaqah: "সাদাকাহ",
    sadaqahDesc: "মসজিদ পরিচালনা ও কমিউনিটি কল্যাণে সাধারণ সহায়তা।",
    zakat: "যাকাত",
    zakatDesc: "নিরাপদ যাচাইসহ আপনার ফরজ যাকাত আদায় করুন।",
    paymentDetails: "পেমেন্ট বিবরণ",
    yourName: "আপনার নাম",
    amount: "পরিমাণ",
    bkashNumber: "বিকাশ নম্বর",
    transactionId: "ট্রানজেকশন আইডি",
    note: "নোট",
    confirmDonation: "অনুদান নিশ্চিত করুন",
    submitting: "পাঠানো হচ্ছে...",
    supportCommunity: "মসজিদ কমিউনিটির বিকাশে অংশ নিন।",
    campaignIntro: "এখানে প্রদর্শিত প্রতিটি ক্যাম্পেইন ওয়েবসাইটের লাইভ ডেটা থেকে নেওয়া।",
    raised: "সংগৃহীত",
    goal: "লক্ষ্য",
    fundraisingCampaign: "তহবিল সংগ্রহ ক্যাম্পেইন",
    raisedSoFar: "এ পর্যন্ত সংগৃহীত",
    progress: "অগ্রগতি",
    status: "অবস্থা",
    active: "চলমান",
    closed: "বন্ধ",
    aboutCampaign: "ক্যাম্পেইন সম্পর্কে",
    howToSupport: "কীভাবে সহায়তা করবেন",
    howToSupportText:
      "ডোনেশন সেন্টার থেকে আপনার বিকাশ নম্বর ও ট্রানজেকশন আইডি দিয়ে অনুদান জমা দিন, যাতে মসজিদ এই ক্যাম্পেইনের সাথে তা যাচাই করতে পারে।",
    goToDonate: "দান পাতায় যান",
    stayConnected: "মসজিদের খবর ও কমিউনিটি নোটিশের সাথে যুক্ত থাকুন।",
    noticeIntro: "ওয়েবসাইট অ্যাডমিন প্যানেল থেকে প্রকাশিত ঘোষণা এখানে দেখা যাবে।",
    announcement: "ঘোষণা",
    islamicGuides: "ইসলামিক গাইড",
    guidesIntro: "স্পষ্টতা, প্রশান্তি ও আধ্যাত্মিক মনোযোগ নিয়ে শিখুন।",
    hadithLibrary: "হাদিস লাইব্রেরি",
    continueReflection: "চিন্তায় অবিরত থাকুন",
    continueReflectionText: "সালাতের গাইড, হাদিস অধ্যয়ন ও নিয়মিত স্মরণে বারবার ফিরে আসুন।",
    unableToLoad: "লাইভ ডেটা লোড করা যায়নি",
    loadingSanctuary: "ডেটা লোড হচ্ছে..."
  },
  en: {
    appName: "Baitun Najat",
    switchLang: "বাং",
    home: "Home",
    homeTab: "Home",
    prayer: "Prayer Timings",
    prayerTab: "Timings",
    gallery: "Gallery",
    donate: "Donate",
    donateTab: "Give",
    guides: "Guides",
    campaigns: "Campaigns",
    announcements: "Announcements",
    notifications: "Notifications",
    notificationsIntro: "Prayer-time changes and important updates appear here.",
    markAllRead: "Mark All Read",
    unread: "Unread",
    read: "Read",
    noNotifications: "No notifications yet.",
    welcomeEyebrow: "Welcome to the Sanctuary",
    welcomeTitle: "A place for peace, prayer, and community.",
    exploreCommunity: "Explore Community",
    viewCampaigns: "View Campaigns",
    todayHijri: "Today's Hijri Date",
    live: "Live",
    upcomingPrayer: "Upcoming Prayer",
    adhan: "Adhan",
    iqamah: "Iqamah",
    fullSchedule: "Full Schedule",
    dailyWisdom: "Daily Wisdom",
    namazGuide: "Namaz Guide",
    guidesHadith: "Guides and hadith library",
    quickLinks: "Quick Links",
    openSection: "Open section",
    recentUpdates: "Recent Updates",
    readMore: "Read More",
    donorNamePlaceholder: "Donor name",
    amountPlaceholder: "1000",
    bkashPlaceholder: "01XXXXXXXXX",
    transactionPlaceholder: "TRX123456",
    notePlaceholder: "Optional note",
    missingFields: "Missing fields",
    missingFieldsText: "Please fill in the required donation details.",
    submitted: "Submitted",
    submittedText: "Donation has been submitted for confirmation.",
    submissionFailed: "Submission failed",
    tryAgain: "Please try again.",
    donorQuote: "\"The believer's shade on the Day of Resurrection will be their charity.\"",
    donorQuoteSource: "Prophet Muhammad (PBUH)",
    sacredSpaces: "Sacred Spaces",
    visualJourney: "A visual journey through Baitun Najat Jame Masjid.",
    allFrames: "All Frames",
    interior: "Interior",
    exterior: "Exterior",
    prayerSpace: "Prayer Space",
    discoverMore: "Discover More Moments",
    currentPrayer: "Current Prayer",
    dailyTimings: "Daily Timings",
    liveSchedule: "Live schedule",
    stepPrayer: "Step-by-Step Prayer",
    stepPrayerDesc: "A visual and textual walkthrough for prayer and purification guidance.",
    investAkhirah: "Invest in your Akhirah",
    donateIntro: "Your generous contributions support the maintenance of the House of Allah and empower our community services.",
    sadaqah: "Sadaqah",
    sadaqahDesc: "General charity for mosque operations and community welfare.",
    zakat: "Zakat",
    zakatDesc: "Fulfill your obligatory duty with secure donation reporting.",
    paymentDetails: "Payment Details",
    yourName: "Your Name",
    amount: "Amount",
    bkashNumber: "bKash Number",
    transactionId: "Transaction ID",
    note: "Note",
    confirmDonation: "Confirm Donation",
    submitting: "Submitting...",
    supportCommunity: "Support the growth of the masjid community.",
    campaignIntro: "Every campaign shown here is synced from the website and reflects current donation progress.",
    raised: "Raised",
    goal: "Goal",
    fundraisingCampaign: "Fundraising Campaign",
    raisedSoFar: "Raised so far",
    progress: "Progress",
    status: "Status",
    active: "Active",
    closed: "Closed",
    aboutCampaign: "About This Campaign",
    howToSupport: "How to Support",
    howToSupportText:
      "Submit your donation with your bKash number and transaction ID from the donation center so the mosque can confirm it against this campaign.",
    goToDonate: "Go To Donate",
    stayConnected: "Stay connected to masjid news and community notices.",
    noticeIntro: "Announcements appear here as they are published from the website admin panel.",
    announcement: "Announcement",
    islamicGuides: "Islamic Guides",
    guidesIntro: "Learn with clarity, calm, and spiritual breathing room.",
    hadithLibrary: "Hadith Library",
    continueReflection: "Continue your reflection",
    continueReflectionText: "Return regularly for prayer guidance, hadith study, and ongoing spiritual reminders.",
    unableToLoad: "Unable to load live data",
    loadingSanctuary: "Loading sanctuary..."
  }
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: PropsWithChildren) {
  const [lang, setLang] = useState<AppLang>("bn");
  const value = useMemo(
    () => ({
      lang,
      setLang,
      toggleLang: () => setLang((current) => (current === "bn" ? "en" : "bn")),
      t: copy[lang]
    }),
    [lang]
  );
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error("useLanguage must be used within LanguageProvider");
  return value;
}
